version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


#services:
  #backend:
    #build: ./backend
    #ports:
      #- "8000:8000"
    #volumes:
      #- ./backend:/app
    #environment:
      #- ENV=dev
    #user: "${UID}:${GID}"
  #frontend:
    #build: ./frontend
    #ports:
      #- "3000:3000"
    #volumes:
      #- ./frontend:/app
    #environment:
      #- ENV=dev
    #user: "${UID}:${GID}"
