global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'main_service'
    static_configs:
      - targets: ['localhost:8001']  # Main service Prometheus metrics

  - job_name: 'demo_login_service'
    static_configs:
      - targets: ['localhost:8000']  # Demo login service Prometheus metrics