name: Push Docker Images to Amazon ECR

on:
  push:
    branches: [ main ]

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.ECR_BACKEND_REPO }}:latest ./backend
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.ECR_FRONTEND_REPO }}:latest ./frontend
    
      - name: Push backend image to ECR
        run: |
            docker push ${{secrets.ECR_BACKEND_REPO}}:latest
      - name: Push frontend image to ECR
        run: |
            docker push ${{secrets.ECR_FRONTEND_REPO}}:latest